### ISSUE TITLE
"Input Type (torch.cuda.FloatTensor) and Weight Type (torch.cuda.HalfTensor) Mismatch"

### ISSUE THREAD

**Issue by CCRss** [SociallyIneptWeeb/AniVoiceChanger#1]
### Hello, when I start recording got this error.
Different types of input and weights.** 
Model, was trained on RVC version 1 not v2. 

### Console Logs
```
Recording has started.
Converting voice...
Traceback (most recent call last):
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\vc_infer_pipeline.py", line 284, in pipeline
    index = faiss.read_index(file_index)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\faiss\swigfaiss.py", line 8261, in read_index
    return _swigfaiss.read_index(*args)
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\logs\mi-test\added_IVF778_Flat_nprobe_1.index for reading: No such file or directory
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\keyboard\_generic.py", line 58, in process
    if self.pre_process_event(event):
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\keyboard\__init__.py", line 213, in pre_process_event
    key_hook(event)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\keyboard\__init__.py", line 516, in <lambda>
    return hook_key(key, lambda e: e.event_type == KEY_DOWN or callback(e), suppress=suppress)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\AniVoiceChanger\main_local.py", line 245, in on_release_key
    rvc_infer()
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\AniVoiceChanger\main_local.py", line 190, in rvc_infer
    audio_opt = vc.pipeline(hubert_model, net_g, 0, audio, INPUT_VOICE_PATH, times, PITCH_CHANGE, PITCH_EXTRACTION_ALGO, index_path, INDEX_RATE, if_f0, 3, tgt_sr, 0, VOLUME_ENVELOPE, version, 0.33, f0_file=None)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\vc_infer_pipeline.py", line 384, in pipeline
    self.vc(
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\vc_infer_pipeline.py", line 185, in vc
    logits = model.extract_features(**inputs)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\fairseq\models\hubert\hubert.py", line 535, in extract_features
    res = self.forward(
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\fairseq\models\hubert\hubert.py", line 437, in forward
    features = self.forward_features(source)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\fairseq\models\hubert\hubert.py", line 392, in forward_features
    features = self.feature_extractor(source)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\fairseq\models\wav2vec\wav2vec2.py", line 895, in forward
    x = conv(x)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\torch\nn\modules\conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "G:\CCR\Рабочий стол\voice_AI\RVC-beta-v2-0618\runtime\lib\site-packages\torch\nn\modules\conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same
```

**Comment by SociallyIneptWeeb** [comment]
Maybe you can try training using v2 and see if you still face the same error? I believe my script only works for v2 trained models.

**Comment by CCRss** [comment]
Yeah, today want to do it. If it will work I will response here. 

> Maybe you can try training using v2 and see if you still face the same error? I believe my script only works for v2 trained models.

**Comment by CCRss** [comment]
Tried with v2 model, same issue

**Comment by CCRss** [comment]
This model work when use Google Collab, but not working locally, I have 1060, might be problem with it graphic card.

**Comment by Quaxdrone** [comment]
Try Update your Graphic Card

**Comment by Wizzarddude305** [comment]
I have a 1070 and I also get the same error, looking at the code it does an if statement declaring that if 1060,1070, or 1080 is in the GPU's name it'd be forced to "single precision". I'm assuming that's what kills the entire operation.

**Comment by SociallyIneptWeeb** [comment]
Could you maybe remove that line in the if and test it? So just delete line 37 in your case and see if it works without

**Comment by Wizzarddude305** [comment]
I tried that and it doesn't work, but I did find the solution. Apparently the real problem is that myinfer.py from the original file was outdated so that series 10 gpu's wouldn't work described in this forum "myinfer.py has not been updated #299". However, I fixed it on my end by implementing the voice changer code that they introduced in the forum. These are the updated functions: `def vc_single(
    sid=0,
    input_audio_path=None,
    f0_up_key=0, 
    f0_file=None,
    f0_method="pm", 
    file_index="", #.index file
    file_index2="",
    # file_big_npy,
    index_rate=1.0, 
    filter_radius=3, 
    resample_sr=0, 
    rms_mix_rate=1.0, 
):
    global tgt_sr, net_g, vc, hubert_model, version
    if input_audio_path is None:
        return "You need to upload an audio file", None
    
    f0_up_key = int(f0_up_key)
    audio = load_audio(input_audio_path, 16000)
    audio_max = np.abs(audio).max() / 0.95
    
    if audio_max > 1:
        audio /= audio_max
    times = [0, 0, 0]
    
    if hubert_model == None:
        load_hubert()
    
    if_f0 = cpt.get("f0", 1)
    
    file_index = (
        (
            file_index.strip(" ")
            .strip('"')
            .strip("\n")
            .strip('"')
            .strip(" ")
            .replace("trained", "added")
        )
        if file_index != ""
        else file_index2
    )
    
    audio_opt = vc.pipeline(
        hubert_model,
        net_g,
        sid,
        audio,
        input_audio_path,
        times,
        f0_up_key,
        f0_method,
        file_index,
        # file_big_npy,
        index_rate,
        if_f0,
        filter_radius,
        tgt_sr,
        resample_sr,
        rms_mix_rate,
        version,
        f0_file=f0_file,
        protect= 0.38
    )
    wavfile.write(OUTPUT_VOICE_PATH, tgt_sr, audio_opt)


def get_vc(model_path):
    global n_spk, tgt_sr, net_g, vc, cpt, version
    print("loading %s" % model_path)   # Changed 'person' to 'model_path'
    cpt = torch.load(model_path, map_location="cpu")  # Changed 'person' to 'model_path'
    tgt_sr = cpt["config"][-1]
    cpt["config"][-3] = cpt["weight"]["emb_g.weight"].shape[0]  
    if_f0 = cpt.get("f0", 1)
    version = cpt.get("version", "v1")
    if version == "v1":
        if if_f0 == 1:
            net_g = SynthesizerTrnMs256NSFsid(*cpt["config"], is_half=config.is_half)
        else:
            net_g = SynthesizerTrnMs256NSFsid_nono(*cpt["config"])
    elif version == "v2":
        if if_f0 == 1:
            net_g = SynthesizerTrnMs768NSFsid(*cpt["config"], is_half=config.is_half)
        else:
            net_g = SynthesizerTrnMs768NSFsid_nono(*cpt["config"])
    del net_g.enc_q
    print(net_g.load_state_dict(cpt["weight"], strict=False))
    net_g.eval().to(config.device)
    if config.is_half:
        net_g = net_g.half()
    else:
        net_g = net_g.float()
    vc = VC(tgt_sr, config)
    n_spk = cpt["config"][-3]
    return {"visible": True, "maximum": n_spk, "__type__": "update"` You're going to have to fix it to fit the mainLocal code, but this is what I made in my custom code.
